### ISSUE TITLE
openbios as a standalone project, roadmap, contributing

### ISSUE THREAD

**Issue by JaCzekanski** [grumpycoders/pcsx-redux#192]
Hello,
I stumbled upon `openbios` subproject in this repo and I have to say that I'm pretty impressed by the efforts with RE and coding - I tried building the BIOS and booting few games using it in my emulator and was able to run few of them (Ridge Racer works perfectly).
I wanted to start a similar project so that emulators/FPGA implementation could use an open-source bios replacement without a need for hacked HLE BIOS approach, but after seeing how much work you already did I decided to help you rather than start from scratch.

Making this project a separate repository would make the contribution, building, licensing much easier.

Is there any todolist/roadmap so that I could start contributing?

**Comment by nicolasnoble** [comment]
Oh wow, I didn't notice people noticed the project :-) I'm not necessarily paying a lot of attention to issues, that's my bad. I think I've noticed you on Discord, so feel free to reach out to me there if you want to have a more direct line of communication.

So I've re licensed the project using the MIT license, since it's fully something from scratch.

The main reason it's in a single repository is to make the whole testing / building / packaging story easier for me at the end of the day, as I don't have to deal with a complex build system for it. Would this really be a deal breaker?

For the todolist / roadmap for the openbios:

 - getting the rest of the memory card stuff to work. That's what I'm currently working on at the moment;
 - paying more attention to games patches, and coming up with solutions for them;
 - filling the rest of the a0/b0/c0 tables with, well, code.

I also don't mind at all sharing my ghidra repository if you want to see the current state of my reverse engineering work. Again, better reach out on Discord for syncing up on this.

**Comment by nicolasnoble** [comment]
Another tangential part of the project ought to be creating a shell for it, in order to help managing memory cards and do various other tasks, possibly including an sioloader and other utilities.

**Comment by nicolasnoble** [comment]
Also, the other thing to consider is that this really is meant to be a "dumb" and straight rewrite, in the sense that I'm not willing to add too many features or fix bugs: it's meant to be educational first.

It might make sense to fork a spinoff somewhere else that'd improve and fix the overall code, in order to make another bios that's less true to the original and more efficient and less buggy. I actually had that in mind.

**Comment by NDR008** [comment]
I think we should target to make unirom the shell.
When unirom has the memory card management and openbions/redux can handle the CD-ROM access - we'll be good

**Comment by nicolasnoble** [comment]
Unirom is in fact the current shell as of a few days ago:

https://github.com/grumpycoders/pcsx-redux/blob/main/azure-pipelines-linux.yml#L32-L54

**Comment by JaCzekanski** [comment]
@nicolasnoble I think we can close this issue - the licensing issue was resolved and I'm okay with having openbios project inside the pcsx-redux repository.

**Comment by davidhedlund** [comment]
> @nicolasnoble I think we can close this issue - the licensing issue was resolved and I'm okay with having openbios project inside the pcsx-redux repository.

I want to list OpenBIOS in the Free Software Directory that I administrate. A separate release would make it more convenient for bug tracking, emulator compability listing, etc.

**Comment by nicolasnoble** [comment]
OpenBIOS can be found in a more stand alone fashion here: https://github.com/pcsx-redux/nugget/tree/main/openbios - as mentioned, it's easier to have everything in a single place due to unit testing.

There is no formal release as the build just lives at head. Bug tracking will still happen here for consistency.
